#!/bin/bash

# ###############
# Git
# #####
function git.pre_commit.init() {
  pre-commit install
  pre-commit install --hook-type pre-push
}

function git.pre_commit.run_for_all() {
  pre-commit run --all-files
}

# ###############
# Requirements
# #####
function requirements.compile() {
  pip install -r requirements/pip-tools.txt
  pip-compile requirements/prod.in
  pip-compile requirements/dev.in
}

function requirements.install() {
  pip install -r requirements/pip-tools.txt
  pip-sync requirements/dev.txt
}

# ###############
# Scripts
# #####
function train() {
  PYTHONPATH=. python framework/scripts/train.py "${@}"
}

function test() {
  PYTHONPATH=. python framework/scripts/test.py "${@}"
}

function tensorboard() {
  PYTHONPATH=. python framework/scripts/tb.py "${@}"
}

# ###############
# Bash completion
# #####
_completions() {
  if [ "${#COMP_WORDS[@]}" != "2" ]; then
    return
  fi

  COMPREPLY=($(compgen -W "$(cat ./runner | grep function | sort | awk 'NR>1{print $2;}' | tr -d "()" | tr '\n' ' ')" -- "${COMP_WORDS[1]}"))
}
complete -F _completions runner

# ###############
# Runner (should be at the end of the file)
# #####
eval "${1}" "${@:2}"
